# Config file
# Commmon for main_clustering.py and probabilities.py
#
# Common directrory for all processing. All other files and folders 
# described below will be created inside this one.
working_dir : "/.../sv-bay-data/" 
# Log file for the first step (includes some bam/sam statistics 
# and clustering information)
clustering_log_file : "main_clustering.log" 
# Log file for the second step (includes information 
# about bayesian models calculation)
probabilites_log_file : "main_probabilities.log"
# Logs verbosity. Setting this to 1 makes sv-bay produce 
# tens of megabytes of logs, so change it only for troubleshooting.
debug : 0
# Number of parallel threads for clustering. SV-Bay works fast 
# even with one process (less then 2 hours for mate-pair data 
# with coverge 12). If the number of processes is more than 1, 
# clustering log would be unordered and very hard to read, so change 
# it only if speed is crucial for you.
clustering_parallel_processes : 1
# Input directory with per-chromosome bam or sam files. 
# Bam should be sorted and indexed, .bam.bai files should 
# be in the same folder. 
# To split whole genome bam you can use utils/separately_save_sam.py.
sam_files_dir : "bam/"
# Internal directory to save normal fragments positions
normal_fragments_dir : "normal_fragments/"
# Input directory with per-chromosome .fa files
fa_files_dir : "fa_files/"
# Input directory with per-chromosome .gem files.
# You can download pre-calculated gem for hg18, hg19, hg38, 
# for read lengths 50,70,100. To split whole genome gem 
# you can use utils/separately_save_gem.py.
gem_files_dir : "gem_files/"
# File with fragment length distribution created by SV-Bay
length_histogram_file : "historam.txt" 
# Input file with information about centromere positions 
# You can download pre-calculated for hg18, hg19, hg38.
centromic_file : "centrom_hg38.txt"
# Internal directory to save clusters containing abnormal fragmetns
clusters_files_dir : "clusters_files/"
# Internal file to save lambda (gc)
lambda_file : "lambda.txt" 
# File to output clusters and probabilities
links_probabilities_file : "links_probabilities.txt" 
# Directory to output valid clusters
valid_links_dir : "valid_links/" 
# Internal file to pass some statistics from
# main_clustering to main_probabilities
serialized_stats_file : "serialized_stats.yaml" 
# Input file, generated by FREEC
cnv_file: "simulated_reads_cnv.txt" 
# Chromosomes to process
chromosomes : ["chr13","chr5","chr11","chr12","chrY"]
# Expected number of structure variants
exp_num_sv: 100 
# Distribution cutoff used when deciding
# whether read is normal or abnorma
alpha : 0.01
# Read length
read_length : 50
# Ploidy
ploidy : 4.0
# Minimum alleles to mark SV as co-amplification
numb_allel : 8
